image: python:3.10

# Define the stages of pipeline
stages:
  - lint
  - test
  - build
  - package_testpypi
  - package_pypi

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Include CI/CD configuration files
include:
  - local: .gitlab/ci/build.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/package.gitlab-ci.yml
  - local: .gitlab/ci/lint.gitlab-ci.yml

cache:
  paths:
    - .cache/pip
    - .venv/
  key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
