# Upload release on RADAR
# This job is run only for release tags, starting with "v"
archive-radar:
  stage: archive
  image: python:3.11
  rules:
  - if: ($CI_COMMIT_TAG =~ /^v/ && $ENABLE_RADAR == "true")
  before_script:
  - pip install FACILE-RS==${FACILE_RS_VERSION}
  script:
  - >
    create_radar
    $RELEASE_ARCHIVE_URL

# Upload release on Zenodo
# This job is run only for release tags, starting with "v"
archive-zenodo:
  stage: archive
  image: python:3.11
  rules:
  - if: ($CI_COMMIT_TAG =~ /^v/ && $ENABLE_ZENODO == "true")
  before_script:
  - pip install FACILE-RS==${FACILE_RS_VERSION}
  script:
  - >
    create_zenodo
    $RELEASE_ARCHIVE_URL

# Create a BagPack archive and upload it to the GitLab registry
archive-bagpack:
  stage: archive
  image: python:3.11
  dependencies:
  - build-datacite
  rules:
  - if: ($CI_COMMIT_TAG =~ /^v/ && $ENABLE_BAGPACK == "true")
  before_script:
  - apt-get update && apt-get install -y curl
  - pip install FACILE-RS==${FACILE_RS_VERSION}
  script:
  - create_bagpack $RELEASE_ARCHIVE_URL
  - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${BAG_PATH} ${BAGPACK_REGISTRY_URL}/${BAG_PATH}'
