# Generate a CFF (Citation File Format) file and export it as an artifact
create-cff:
  image: python:3.11
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH
  before_script:
  - pip install FACILE-RS==${FACILE_RS_VERSION}
  - git config --global user.name "${GITLAB_USER_NAME}"
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
  - facile-rs cff create
  # Uncomment the following lines if you want to commit and push the CFF file to your repository
  # - git add ${CFF_PATH}
  # # Commit only if CFF file has been updated
  # - git diff-index --quiet HEAD || git commit -m 'Update CFF file'
  # # Push to the repository, but do not trigger CI
  # - git push -o ci.skip "https://PUSH_TOKEN:${PRIVATE_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_BRANCH}"
  artifacts:
    paths:
    - ${CFF_PATH}
    expire_in: 2 hrs
  
