testuv-uv-build:
  stage: build
  script:
    - export UV_LINK_MODE=copy
    - export UV_NO_CACHE=1
    - uv build --no-cache --no-build-isolation
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
