build:package:
  stage: build
  before_script:
    - pip install -U pip
    - pip install poetry
  script:
    - poetry install
    - poetry build
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"
    - changes:
        - ".gitlab/ci/build.gitlab-ci.yml"
        - "neptoon/**/*"
        - "tests/**/*"
        - ".gitlab-ci.yml"
        - "poetry.lock"
        - "pyproject.toml"
  artifacts:
    paths:
      - dist/
