## WIP

docker-build:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: docker
  tags:
    - dind
  script:
    - VERSION=`echo $CI_COMMIT_TAG | grep -oP '^pre-\K.*$'`
    - docker build \
      --build-arg PACKAGE_VERSION=${VERSION} \
      -t neptoon:${VERSION} .
