variables:
  REGISTRY_BASE: "registry.hzdr.de/cosmos/neptoon"
  PLATFORMS: "linux/amd64,linux/arm64"

# Test Builds
docker-test-image-gui:
  stage: docker
  image: docker:24.0.5
  tags:
    - dind
  services:
    - name: docker:24.0.5-dind
      command: ["--experimental"]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_CLI_EXPERIMENTAL: enabled
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker info
    - docker buildx create --name mybuilder --driver docker-container --bootstrap
    - docker buildx use mybuilder
    - docker buildx inspect --bootstrap
  script:
    - |
      docker buildx build \
        --platform $PLATFORMS \
        --file .dock-gui.Dockerfile \
        --tag "$REGISTRY_BASE/neptoon-gui:test-$CI_COMMIT_SHORT_SHA" \
        --push \
        .
    - echo "Test image pushed - registry.hzdr.de/cosmos/neptoon/neptoon-gui:test-$CI_COMMIT_SHORT_SHA"
  after_script:
    - docker buildx rm mybuilder || true
  rules:
    - if: $CI_COMMIT_TAG == "docker-test"

docker-test-image-cli:
  stage: docker
  image: docker:24.0.5
  tags:
    - dind
  services:
    - name: docker:24.0.5-dind
      command: ["--experimental"]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_CLI_EXPERIMENTAL: enabled
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker info
    - docker buildx create --name mybuilder --driver docker-container --bootstrap
    - docker buildx use mybuilder
    - docker buildx inspect --bootstrap
  script:
    - |
      docker buildx build \
        --platform $PLATFORMS \
        --file .dock-cli.Dockerfile \
        --tag "$REGISTRY_BASE/neptoon-cli:test-$CI_COMMIT_SHORT_SHA" \
        --push \
        .
    - echo "✅ Multi-platform test image pushed - registry.hzdr.de/cosmos/neptoon/neptoon-cli:test-$CI_COMMIT_SHORT_SHA"
  after_script:
    - docker buildx rm mybuilder || true
  rules:
    - if: $CI_COMMIT_TAG == "docker-test"

# Production builds
docker-build-image-gui:
  stage: docker
  image: docker:24.0.5
  tags:
    - dind
  services:
    - name: docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker info
  script:
    - docker build -f .dock-gui.Dockerfile -t "$REGISTRY_BASE/neptoon-gui:$CI_COMMIT_TAG" .
    - docker push "$REGISTRY_BASE/neptoon-gui:$CI_COMMIT_TAG"
    - docker tag "$REGISTRY_BASE/neptoon-gui:$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE/neptoon-gui:latest"
    - docker push "$REGISTRY_BASE/neptoon-gui:latest"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/

docker-build-image-cli:
  stage: docker
  image: docker:24.0.5
  tags:
    - dind
  services:
    - name: docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker info
  script:
    - docker build -f .dock-cli.Dockerfile -t "$REGISTRY_BASE/neptoon-cli:$CI_COMMIT_TAG" .
    - docker push "$REGISTRY_BASE/neptoon-cli:$CI_COMMIT_TAG"
    - docker tag "$REGISTRY_BASE/neptoon-cli:$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE/neptoon-cli:latest"
    - docker push "$REGISTRY_BASE/neptoon-cli:latest"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
