test:flake8:
  stage: lint
  image: ghcr.io/astral-sh/uv:python3.11-bookworm
  before_script:
    - uv run
    - uv pip install flake8
  script:
    - flake8 .
    - uv cache prune --ci
  cache:
    paths:
      - "$UV_CACHE_DIR"
      - .cache/pip
      - .venv/
    key:
      files:
        - pyproject.toml
      prefix: ${CI_JOB_NAME}
