variables:
  UV_LINK_MODE: copy

package_testpypi:
  stage: package_testpypi
  # needs:
  #   - build:package
  before_script:
    - rm -rf .uv-cache
    - uv cache clean
    - uv build --no-cache
  script:
    - uv publish --publish-url https://test.pypi.org/legacy/ --token "${neptoon_pypi_test_api_key}"
    # - poetry config repositories.testpypi "https://test.pypi.org/legacy/"
    # - poetry publish -r testpypi -u "__token__" -p "${neptoon_pypi_test_api_key}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/

package_pypi:
  stage: package_pypi
  # needs:
  #   - build:package
  before_script:
    - rm -rf .uv-cache
    - uv cache clean
    - uv build --no-cache
  script:
    # - poetry publish -u "__token__" -p "${neptoon_pypi_api_key_ACTUAL}"
    - uv publish --token "${neptoon_pypi_api_key_ACTUAL}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
      when: manual
