package_testpypi:
  stage: package_testpypi
  script:
    - export UV_LINK_MODE=copy
    - export UV_NO_CACHE=1
    - uv build --no-cache --no-build-isolation
    - uv publish --publish-url https://test.pypi.org/legacy/ --token "${neptoon_pypi_test_api_key}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/

package_pypi:
  stage: package_pypi
  before_script:
    - rm -rf .uv-cache
    - uv cache clean
  script:
    - export UV_LINK_MODE=copy
    - uv build --no-cache
    - uv publish --token "${neptoon_pypi_api_key_ACTUAL}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
      when: manual
